# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CBDS Calculator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CBDS Calculator
    pod 'Firebase/Analytics'
    pod 'Firebase/Auth'
    pod 'Firebase/Core'
    pod 'Firebase/Firestore'

end
